upstream telliapps_website {
  server 127.0.0.1:8088;
  keepalive 16;
}

server {
  listen 80;
  listen [::]:80;
  server_name
    telli-apps.de
    www.telli-apps.de
    planteller.telli-apps.de
    planparty.telli-apps.de;

  access_log /var/log/nginx/telliapps.access.log;
  error_log /var/log/nginx/telliapps.error.log;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  location / {
    proxy_pass http://telliapps_website;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_hide_header X-Powered-By;
  }
}
