services:
  website:
    build:
      context: ..
      args:
        PUBLIC_UMAMI_SRC: ${PUBLIC_UMAMI_SRC:-}
        PUBLIC_UMAMI_WEBSITE_ID: ${PUBLIC_UMAMI_WEBSITE_ID:-}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:8080"
